const STORAGE_KEY='hub-inteligencia-comercial-v1';
const statusOptions=['Planejado','Em andamento','Concluído','Atrasado','Aguardando','Cancelado'];
const menu=[
 ['home','🏠','Visão Geral','Home com os principais indicadores comerciais por negócio.'],
 ['calendario','📅','Calendário Comercial','Planejamento das campanhas, ações e marcos comerciais.'],
 ['internas','🏢','Ações Internas','Ações internas do Grupo Dom Bosco.'],
 ['externas','🌎','Ações Externas','Ações externas, visitas, feiras e captação em campo.'],
 ['dom-bosco','🏫','Escola Dom Bosco','Acompanhamento comercial da Escola Dom Bosco.'],
 ['undb','🎓','UNDB Graduação','Acompanhamento comercial da graduação.'],
 ['pos','🎯','Pós-Graduação','Acompanhamento comercial da Pós-Graduação.'],
 ['medicina','🩺','Medicina','Processos seletivos, inscritos e links dos dashboards.'],
 ['eventos','🎪','Eventos','Eventos realizados, planejados, leads e custos.'],
 ['reunioes','🤝','Reunião Comercial','Demandas das reuniões de segunda-feira.'],
 ['config','⚙️','Configurações','Links CSV e Power BI.']
];
const schemas={
 calendario:['periodo','instituicoes','tema','descricao','canais','responsavel','status','totalLeads','leadsUNDB','leadsDB','leadsPOS','investimento','observacoes'],
 internas:['periodo','instituicoes','tema','descricao','canais','responsavel','status','totalLeads','leadsUNDB','leadsDB','leadsPOS','investimento','observacoes'],
 externas:['periodo','instituicoes','tema','descricao','canais','responsavel','status','totalLeads','leadsUNDB','leadsDB','leadsPOS','investimento','observacoes'],
 domBosco:['periodo','instituicoes','tema','descricao','canais','responsavel','status','totalLeads','leadsUNDB','leadsDB','leadsPOS','investimento','observacoes'],
 undb:['periodo','instituicoes','tema','descricao','canais','responsavel','status','totalLeads','leadsUNDB','leadsDB','leadsPOS','investimento','observacoes'],
 pos:['periodo','instituicoes','tema','descricao','canais','responsavel','status','totalLeads','leadsUNDB','leadsDB','leadsPOS','investimento','observacoes'],
 medicina:['periodo','instituicoes','tema','descricao','canais','responsavel','status','totalLeads','leadsUNDB','leadsDB','leadsPOS','investimento','observacoes'],
 eventos:['data','evento','negocio','responsavel','status','leadsDB','leadsUNDB','leadsPOS','investimento','cpl','observacoes'],
 reunioes:['data','bloco','responsavel','tarefa','prazo','status','observacoes']
};
const labels={periodo:'Período',instituicoes:'Instituições',tema:'Tema',descricao:'Descrição',canais:'Canais',responsavel:'Responsável',status:'Status',totalLeads:'Total Leads',leadsUNDB:'Leads UNDB',leadsDB:'Leads DB',leadsPOS:'Leads Pós',investimento:'Investimento',observacoes:'Observações',data:'Data',evento:'Evento',negocio:'Negócio',cpl:'CPL',bloco:'Bloco',tarefa:'Tarefa/Demanda',prazo:'Prazo'};
let state=getDefaultState();
function getDefaultState(){return {home:[
 {titulo:'Matrículas 2026.2 UNDB',valor:'--',fonte:'Fonte: RM / Power BI UNDB',descricao:'Graduação UNDB',tipo:'primary'},
 {titulo:'Matrículas Dom Bosco 2026',valor:'--',fonte:'Fonte: RM / Power BI Escola',descricao:'Escola Dom Bosco',tipo:'primary'},
 {titulo:'Matrículas Medicina 2026.2',valor:'--',fonte:'Fonte: RM / Power BI Medicina',descricao:'Medicina',tipo:'primary'},
 {titulo:'Inscritos no vestibular de Med',valor:'--',fonte:'Processo seletivo tradicional',descricao:'Vestibular Medicina',tipo:'normal'},
 {titulo:'Inscritos ENEM Med',valor:'--',fonte:'Entrada via ENEM',descricao:'Medicina ENEM',tipo:'normal'},
 {titulo:'Inscritos Transferência Externa Med',valor:'--',fonte:'Transferência externa Medicina',descricao:'Transferência Medicina',tipo:'normal'}],
 calendario:[row('Julho','UNDB; Medicina','Clínica de Férias','Experiência prática para acadêmicos da saúde','Instagram, Google, WhatsApp','Marketing + Comercial','Planejado'),row('Agosto','Dom Bosco','Campanha Matrícula 2026','Abertura da campanha de captação','Meta, Google, WhatsApp','Ilana','Em andamento')],
 internas:[row('Julho','Grupo Dom Bosco','Alinhamento comercial','Ação interna de acompanhamento das metas','Reunião, WhatsApp','Nathalia','Planejado')],
 externas:[row('Junho','UNDB; Dom Bosco; Pós','Ação externa captação','Captação de leads em evento externo','Evento externo, QR Code, WhatsApp','Marketing','Em andamento')],
 domBosco:[row('Agosto','Dom Bosco','Reserva de Vagas','Acompanhamento da campanha de reserva','WhatsApp, Meta, Google','Ilana','Planejado')],
 undb:[row('Julho','UNDB','Graduação 2026.2','Acompanhamento dos cursos de graduação','Google, Meta, WhatsApp','Allyson','Planejado')],
 pos:[row('Julho','Pós-UNDB','Semana da Especialização','Captação para cursos de Pós-Graduação','Instagram, WhatsApp','Marketing + Pós','Planejado')],
 medicina:[row('Julho','Medicina','Processos Seletivos Medicina','Acompanhamento de vestibular, ENEM e transferência externa','Power BI, WhatsApp, Google','Allyson','Em andamento')],
 eventos:[{data:'2026-07-01',evento:'Clínica de Férias',negocio:'UNDB',responsavel:'Marketing',status:'Planejado',leadsDB:'0',leadsUNDB:'0',leadsPOS:'0',investimento:'0',cpl:'0',observacoes:''}],
 reunioes:[{data:'2026-07-06',bloco:'Dom Bosco - Ilana',responsavel:'Ilana',tarefa:'Atualizar status da captação da Escola',prazo:'2026-07-10',status:'Planejado',observacoes:''},{data:'2026-07-06',bloco:'UNDB e Medicina - Allyson',responsavel:'Allyson',tarefa:'Validar inscritos e matrículas de Medicina',prazo:'2026-07-10',status:'Planejado',observacoes:''},{data:'2026-07-06',bloco:'Ações - Marketing',responsavel:'Rafaela',tarefa:'Atualizar calendário de ações internas e externas',prazo:'2026-07-10',status:'Planejado',observacoes:''}],
 config: JSON.parse(JSON.stringify(window.HUB_CONFIG||{csv:{},powerbi:{}}))};}
function row(periodo,instituicoes,tema,descricao,canais,responsavel,status){return {periodo,instituicoes,tema,descricao,canais,responsavel,status,totalLeads:'0',leadsUNDB:'0',leadsDB:'0',leadsPOS:'0',investimento:'0',observacoes:''}}
function load(){try{const saved=localStorage.getItem(STORAGE_KEY); if(saved) state={...state,...JSON.parse(saved)};}catch(e){console.warn(e)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); toast('Alterações salvas.');}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function initMenu(){const el=document.getElementById('menu');el.innerHTML='';menu.forEach(([id,icon,title])=>{const b=document.createElement('button');b.innerHTML=`<span>${icon}</span>${title}`;b.dataset.view=id;b.onclick=()=>navigate(id);el.appendChild(b)})}
function navigate(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+id).classList.add('active');document.querySelectorAll('.menu button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const item=menu.find(m=>m[0]===id);document.getElementById('pageTitle').textContent=item[2];document.getElementById('pageSubtitle').textContent=item[3];location.hash=id;}
function renderHome(){const v=document.getElementById('view-home');v.innerHTML=`<div class="hero"><h2>Indicadores principais</h2><p>Home limpa com os principais números comerciais por negócio. Todos os campos são editáveis.</p></div><div class="grid kpi-grid" id="homeKpis"></div><div class="panel"><div class="panel-head"><div><h2>Editar indicadores da Home</h2><p>Edite título, número, fonte e descrição.</p></div><button class="btn add-home">+ Novo indicador</button></div><div class="table-wrap"><table id="homeTable"></table></div></div>`;const k=document.getElementById('homeKpis');state.home.forEach(c=>{k.insertAdjacentHTML('beforeend',`<div class="kpi ${c.tipo==='primary'?'primary':''}"><label>${escapeHtml(c.titulo)}</label><div class="value">${escapeHtml(c.valor)}</div><small>${escapeHtml(c.fonte)}</small></div>`)});renderEditableTable('homeTable','home',['titulo','valor','fonte','descricao','tipo']);v.querySelector('.add-home').onclick=()=>{state.home.push({titulo:'Novo indicador',valor:'0',fonte:'Fonte',descricao:'Descrição',tipo:'normal'});renderAll();}}
function renderEditableTable(tableId,key,cols){const table=document.getElementById(tableId);table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${labels[c]||c}</th>`).join('')+'<th>Ações</th></tr></thead><tbody></tbody>';const tb=table.querySelector('tbody');state[key].forEach((item,i)=>{const tr=document.createElement('tr');cols.forEach(c=>{const td=document.createElement('td');td.appendChild(inputFor(key,i,c,item[c]??''));tr.appendChild(td)});const td=document.createElement('td');const del=document.createElement('button');del.className='btn danger';del.textContent='Excluir';del.onclick=()=>{if(confirm('Excluir esta linha?')){state[key].splice(i,1);renderAll();}};td.appendChild(del);tr.appendChild(td);tb.appendChild(tr)})}
function inputFor(key,i,c,value){let el;if(c==='status'){el=document.createElement('select');statusOptions.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;o.selected=s===value;el.appendChild(o)})}else if(['descricao','observacoes','tarefa'].includes(c)){el=document.createElement('textarea');el.value=value}else if(['data','prazo'].includes(c)){el=document.createElement('input');el.type='date';el.value=value}else{el=document.createElement('input');el.type='text';el.value=value}el.oninput=()=>{state[key][i][c]=el.value};return el;}
function renderDataView(key,title,subtitle){const v=document.getElementById('view-'+key.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()));const tpl=document.getElementById('tableTemplate').content.cloneNode(true);tpl.querySelector('h2').textContent=title;tpl.querySelector('p').textContent=subtitle;tpl.querySelector('table').id='table-'+key;v.innerHTML='';v.appendChild(tpl);renderEditableTable('table-'+key,key,schemas[key]);v.querySelector('.add-row').onclick=()=>{const obj={};schemas[key].forEach(c=>obj[c]=c==='status'?'Planejado':'');state[key].push(obj);renderAll();};v.querySelector('.search').oninput=(e)=>filterTable('table-'+key,e.target.value);if(['medicina','domBosco'].includes(key)){const p=key==='medicina'?state.config.powerbi.medicina:state.config.powerbi.domBosco;v.insertAdjacentHTML('afterbegin',`<div class="hero"><h2>Dashboard Power BI</h2><p>Acesse o painel completo.</p><div class="powerbi-box"><a class="btn primary" target="_blank" href="${p||'#'}">Abrir Power BI</a></div></div>`)}if(key==='undb'){v.insertAdjacentHTML('afterbegin',`<div class="hero"><h2>UNDB Graduação</h2><p>Todos os campos abaixo são editáveis, incluindo status.</p></div>`)} }
function filterTable(id,q){q=q.toLowerCase();document.querySelectorAll(`#${id} tbody tr`).forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q)?'':'none')}
function renderConfig(){const v=document.getElementById('view-config');v.innerHTML=`<div class="hero"><h2>Configurações</h2><p>Cole aqui links CSV das abas da planilha e links dos dashboards Power BI. Depois clique em Salvar.</p></div><div class="panel"><div class="panel-head"><div><h2>Links CSV da planilha</h2><p>Deixe vazio para usar edição manual/local.</p></div></div><div class="config-grid" id="csvGrid"></div></div><div class="panel"><div class="panel-head"><div><h2>Links Power BI</h2><p>Botões de acesso dos dashboards.</p></div></div><div class="config-grid" id="powerGrid"></div></div>`;const cg=v.querySelector('#csvGrid');Object.keys(state.config.csv).forEach(k=>cg.appendChild(configInput('csv',k)));const pg=v.querySelector('#powerGrid');Object.keys(state.config.powerbi).forEach(k=>pg.appendChild(configInput('powerbi',k)))}
function configInput(group,k){const d=document.createElement('div');d.className='config-item';d.innerHTML=`<label>${k}</label>`;const inp=document.createElement('input');inp.value=state.config[group][k]||'';inp.oninput=()=>state.config[group][k]=inp.value;d.appendChild(inp);return d}
async function loadCsvConfigured(){for(const [key,url] of Object.entries(state.config.csv||{})){if(!url) continue;try{const res=await fetch(url);const text=await res.text();const rows=parseCsv(text);if(rows.length) state[key]=rows;}catch(e){console.warn('Falha CSV',key,e)}}renderAll(false)}
function parseCsv(text){const lines=text.trim().split(/\r?\n/);if(lines.length<2)return[];const headers=splitCsvLine(lines[0]).map(h=>h.trim());return lines.slice(1).filter(Boolean).map(line=>{const vals=splitCsvLine(line);const o={};headers.forEach((h,i)=>o[h]=vals[i]||'');return o})}
function splitCsvLine(line){let arr=[],cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){q=!q;continue}if(ch===','&&!q){arr.push(cur);cur='';continue}cur+=ch}arr.push(cur);return arr}
function renderAll(loadRemote=true){renderHome();renderDataView('calendario','Calendário Comercial','Planejamento geral das campanhas e ações.');renderDataView('internas','Ações Internas','Ações internas do Grupo Dom Bosco.');renderDataView('externas','Ações Externas','Ações externas e captação em campo.');renderDataView('domBosco','Escola Dom Bosco','Indicadores, ações e acompanhamento comercial da Escola.');renderDataView('undb','UNDB Graduação','Indicadores, ações e acompanhamento comercial da graduação.');renderDataView('pos','Pós-Graduação','Indicadores, ações e acompanhamento comercial da Pós.');renderDataView('medicina','Medicina','Processos seletivos de Medicina, ENEM, transferência e vestibulares.');renderDataView('eventos','Eventos','Eventos, leads por negócio, investimento e status.');renderDataView('reunioes','Reunião Comercial','Data, bloco, responsável, tarefa, prazo, status e observações.');renderConfig(); if(loadRemote){} }
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
document.getElementById('btnSaveAll').onclick=save;document.getElementById('btnExport').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hub-inteligencia-comercial-backup.json';a.click()};document.getElementById('btnImport').onclick=()=>document.getElementById('fileImport').click();document.getElementById('fileImport').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);save();renderAll();};r.readAsText(f)};
load();initMenu();renderAll();navigate((location.hash||'#home').slice(1));loadCsvConfigured();
